int mposx, mposy;
int sclength = 1263;
int scheight = 593;
int level = 0;
int playercorx = 350;
int playercory = 50;
int playerattackindex = 0;
int enemycorx = 700;
int enemycory = 20;
int enemyheight = 400;
int enemywidth = 400;
int enemyattackindex = 0;
bool onair = false;
int countjump = 0;
int jumpindex = 0;
int charheight = 300;
int charwidth = 300;
bool attack = false;
bool run = false;
int runindex = 0;
bool enemymove = false;
bool enemyfight = false;
int shieldindex = 0;
int playerhealthbarx;
int enemyhealthbarx;
int playerhealth = 300;
int enemyhealth = 50 * (level + 1);
int score=0;
bool gameon=true;
bool shield = true;
void new_level()
{
	playercorx = 350;
	playercory = 50;
	playerattackindex = 0;
	enemycorx = 700;
	enemycory = 20;
	enemyheight = 400;
	enemywidth = 400;
	enemyattackindex = 0;
	onair = false;
	countjump = 0;
	jumpindex = 0;
	charheight = 300;
	charwidth = 300;
	attack = false;
	run = false;
	runindex = 0;
	enemymove = false;
	enemyfight = false;
	shieldindex = 0;
	playerhealthbarx=playerhealth;
	enemyhealthbarx=enemyhealth;
	playerhealth = 300;
	enemyhealth = 50 * (level + 1);
	gameon = true;
	shield = true;
}